# --set appimage=${appRegistry}:${BUILD_NUMBER} --set dbimage=${dbRegistry}:latest --set rmqimage=${rmqRegistry}:latest --namespace prod
#         appRegistry = '568406210619.dkr.ecr.ap-southeast-1.amazonaws.com/vprocontainers/vprofileapp'
        # dbRegistry = '568406210619.dkr.ecr.ap-southeast-1.amazonaws.com/vprocontainers/vprofiledb'
        # rmqRegistry = '568406210619.dkr.ecr.ap-southeast-1.amazonaws.com/vprocontainers/vprofilermq'

Global:
  Repository: 568406210619.dkr.ecr.ap-southeast-1.amazonaws.com/vprocontainers

App:
  Image: vprofileapp
  Tag: latest
  Port: 8080

DB:
  Image: vprofiledb
  Tag: latest
  Port: 3306

RMQ:
  Image: vprofilermq
  Tag: latest
  Port: 15672