apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - host: a167e2bde3e3f4761b4511170e61af85-b2012489b3b00ca3.elb.ap-southeast-1.amazonaws.com
        path: /
        pathType: Prefix
        backend:
          service:
            name: vproapp-service
            port:
              number: 8080
