apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: {{ .Values.DB.Replicas }}
  template: 
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vprofile"
        vault.hashicorp.com/agent-inject-secret-database-config.sh: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config.sh: |
          {{`{{- with secret `}}"internal/data/database/config"{{` -}}`}}
            #!/bin/sh
            export MYSQL_ROOT_PASSWORD="{{`{{ .Data.data.password }}`}}"
          {{`{{- end }}`}}
      labels:
        app: vprodb
    spec:
      serviceAccountName: vprosa
      containers:
      - name: vprodb
        image: "{{ .Values.Global.Repository }}/{{ .Values.DB.Image }}:{{ .Values.DB.Tag }}"
        ports:
        - name: vprodb-port
          containerPort: {{ .Values.DB.Port }}