apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vprofile"
        vault.hashicorp.com/agent-inject-secret-database-config: "internal/data/database/config"
      labels:
        app: vprodb
    spec:
      serviceAccountName: vprosa
      containers:
      - name: vprodb
        image: vprofile/vprofiledb
        ports:
        - name: vprodb-port
          containerPort: 3306
        env: 
         - name: MYSQL_ROOT_PASSWORD
           vauleFrom:
             secretKeyRef:
               name: app-secret
               key: db-pass