apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template: 
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vprofile"
        vault.hashicorp.com/agent-inject-secret-database-config.sh: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{`{{- with secret `}}"internal/data/database/config"{{` -}}`}}
            #!/bin/sh
            export MYSQL_ROOT_PASSWORD="{{`{{ .Data.data.password }}`}}"
          {{`{{- end }}`}}
      labels:
        app: vprodb
    spec:
      serviceAccountName: vprosa
      # initContainers:
      #   - name: init
      #     image: alpine
      #     command: ["/bin/sh", "-c", "chmod +x /vault/secrets/database-config"]
      containers:
      - name: vprodb
        image: {{.Values.dbimage}}
        ports:
        - name: vprodb-port
          containerPort: 3306