apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template: 
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vprofile"
        vault.hashicorp.com/agent-inject-secret-database-config: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{`{{- with secret `}}"internal/data/database/config"{{` -}}`}}
            export MYSQL_ROOT_PASSWORD="{{`{{ .Data.data.password }}`}}"
          {{`{{- end }}`}}
      labels:
        app: vprodb
    spec:
      serviceAccountName: vprosa
      containers:
      - name: vprodb
        image: vprofile/vprofiledb
        # command:
        #   ['sh', '-c']
        # args:
        #   ['source /vault/secrets/database/config']
        ports:
        - name: vprodb-port
          containerPort: 3306
        env: 
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: db-pass